batch_size: 8
beam_size: 5
compute_type: auto
condition_on_previous_text: true
cpu_threads: 4
device: cuda
gemini_model: "gemini-2.5-pro"
language: it
num_workers: 1
temperature: 0
whisper_model: tiny
word_timestamps: false
